[package]
name = "nexus"
version = "0.2.0"
description = "Nexus — Local-First Project Control Center"
authors = ["Rafiq Technologies"]
license = "MIT"
edition = "2021"

[lib]
name = "nexus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", features = ["windows-native", "apple-native", "sync-secret-service"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "gzip"] }
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
tokio = { version = "1", features = ["net", "time", "rt", "macros"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
x509-parser = "0.16"
tauri-plugin-notification = "2.3.3"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
sysinfo = "0.39"
dirs = "5"
