import { save } from '@tauri-apps/plugin-dialog';
import { invoke } from '@tauri-apps/api/core';
import type { Project, ProjectStatus } from '../types';
import { getIncidents, getUptimeStats, uptimePct } from './history';
import type { Incident } from './history';
import { getSetting } from './db';
import type { DepsReport } from '../adapters/deps';

// The handover document is intentionally generated in ENGLISH regardless of
// the UI language — it is consumed by AI coding assistants (Claude Code,
// Codex, Cursor), where English is the most reliable and token-efficient.

function line(parts: Array<string | null | undefined | false>): string {
  return parts.filter(Boolean).join(' · ');
}

/** Date part of an ISO string; tolerates malformed upstream payloads. */
function day(s: string | null | undefined): string {
  return typeof s === 'string' && s.length >= 10 ? s.slice(0, 10) : '?';
}

function fmtDuration(startIso: string, endIso: string | null): string {
  const end = endIso ? new Date(endIso).getTime() : Date.now();
  const ms = end - new Date(startIso).getTime();
  if (!Number.isFinite(ms) || ms < 0) return '?';
  const min = Math.round(ms / 60000);
  if (min < 60) return `${min}m`;
  const h = Math.floor(min / 60);
  if (h < 24) return `${h}h ${min % 60}m`;
  return `${Math.floor(h / 24)}d ${h % 24}h`;
}

function incidentLine(i: Incident): string {
  const when = i.startedAt.slice(0, 16).replace('T', ' ');
  const state = i.endedAt === null ? 'ONGOING' : `resolved in ${fmtDuration(i.startedAt, i.endedAt)}`;
  const err = i.firstError ? ` — ${i.firstError.slice(0, 120)}` : '';
  return `- ${when} UTC · ${i.severity} · ${state}${err}`;
}

/**
 * Build a markdown handover/context document for AI coding assistants from
 * everything Nexus knows about the project right now.
 */
export async function buildHandoverDoc(
  project: Project,
  status: ProjectStatus | undefined,
): Promise<string> {
  const now = new Date().toISOString();
  const out: string[] = [];

  out.push(`# ${project.name} — Project Handover`);
  out.push('');
  out.push(`> Generated by Nexus on ${now}. Paste this into an AI coding session to prime it with the project's current operational context.`);
  out.push('');

  // ── Overview ────────────────────────────────────────────────────────────
  out.push('## Overview');
  out.push('');
  if (project.description) out.push(project.description, '');
  const links: string[] = [];
  if (project.repoUrl) links.push(`- Repository: ${project.repoUrl}`);
  if (project.docsUrl) links.push(`- Documentation: ${project.docsUrl}`);
  if (project.apiBaseUrl) links.push(`- API base: ${project.apiBaseUrl}`);
  if (project.deployEndpoint) links.push(`- Deploy endpoint: ${project.deployEndpoint}`);
  if (links.length > 0) out.push(...links, '');

  // ── Current status ──────────────────────────────────────────────────────
  out.push('## Current Status');
  out.push('');
  if (status) {
    out.push(
      line([
        `Health: **${status.health}**`,
        status.latencyMs !== null && `latency ${status.latencyMs} ms`,
        status.httpStatus !== null && `HTTP ${status.httpStatus}`,
        status.checkedAt && `checked at ${status.checkedAt}`,
      ]),
    );
    if (status.error) out.push(`Error: ${status.error}`);
    if (status.healthMeta) {
      const m = status.healthMeta;
      const meta = line([m.app, m.version && `v${m.version}`, m.environment, m.status]);
      if (meta) out.push(`Reported by service: ${meta}`);
    }
    const badComponents = (status.healthComponents ?? []).filter(c => !c.ok);
    if (badComponents.length > 0) {
      out.push('', 'Degraded components:');
      for (const c of badComponents) {
        out.push(`- ${c.group}/${c.name}: ${c.status}${c.error ? ` — ${c.error}` : ''}`);
      }
    }
    if (status.ssl) {
      const s = status.ssl;
      out.push(
        '',
        line([
          `SSL (${s.host}):`,
          s.daysLeft !== null && `${s.daysLeft} days left`,
          s.expiresAt && `expires ${day(s.expiresAt)}`,
          s.issuer && `issuer ${s.issuer}`,
          s.error && `error: ${s.error}`,
        ]),
      );
    }
  } else {
    out.push('No status data yet (project not checked in this session).');
  }
  out.push('');

  // ── Uptime + incidents ──────────────────────────────────────────────────
  try {
    const since7d = new Date(Date.now() - 7 * 86_400_000).toISOString();
    const since30d = new Date(Date.now() - 30 * 86_400_000).toISOString();
    const [u7, u30, incidents] = await Promise.all([
      getUptimeStats(project.id, since7d),
      getUptimeStats(project.id, since30d),
      getIncidents(project.id, 5),
    ]);
    const p7 = uptimePct(u7);
    const p30 = uptimePct(u30);
    if (p7 !== null || p30 !== null || incidents.length > 0) {
      out.push('## Reliability');
      out.push('');
      if (p7 !== null || p30 !== null) {
        out.push(
          line([
            p7 !== null && `Uptime 7d: ${p7.toFixed(1)}%`,
            p30 !== null && `Uptime 30d: ${p30.toFixed(1)}%`,
          ]),
          '',
        );
      }
      if (incidents.length > 0) {
        out.push('Recent incidents (latest 5):');
        out.push(...incidents.map(incidentLine));
        out.push('');
      }
    }
  } catch {
    // History tables unavailable — skip the section rather than fail the doc.
  }

  // ── Git activity ────────────────────────────────────────────────────────
  if (status?.git) {
    const g = status.git;
    out.push('## Git Activity');
    out.push('');
    out.push(
      line([
        `Open MRs/PRs: ${g.openMrCount}`,
        g.failedPipelines !== null && `failed pipelines (recent): ${g.failedPipelines}`,
        g.branches.length > 0 && `branches: ${g.branches.length}`,
      ]),
      '',
    );
    if (g.commits.length > 0) {
      out.push('Recent commits:');
      for (const c of g.commits) {
        out.push(`- ${day(c.date)} ${c.author}: ${c.message}`);
      }
      out.push('');
    }
    if (g.mrs.length > 0) {
      out.push('Open MRs/PRs:');
      for (const mr of g.mrs) {
        out.push(`- ${mr.title}${mr.author ? ` (by ${mr.author})` : ''}`);
      }
      out.push('');
    }
  }

  // ── Tickets ─────────────────────────────────────────────────────────────
  if (status?.tickets && status.tickets.length > 0) {
    const open = status.tickets.filter(
      tk => !['resolved', 'closed'].includes(tk.status.toLowerCase()),
    );
    out.push('## Support Tickets');
    out.push('');
    out.push(`${open.length} open of ${status.tickets.length} total.`);
    if (open.length > 0) {
      out.push('');
      for (const tk of open.slice(0, 10)) {
        out.push(
          `- [${tk.ref}] ${tk.subject} · ${tk.status}${tk.priority ? ` · ${tk.priority}` : ''} · updated ${day(tk.updatedAt)}`,
        );
      }
      if (open.length > 10) out.push(`- …and ${open.length - 10} more`);
    }
    out.push('');
  }

  // ── Dependencies (from the last persisted check, if any) ────────────────
  try {
    const rawReport = await getSetting(`deps_report_${project.id}`);
    if (rawReport) {
      const report = JSON.parse(rawReport) as DepsReport;
      if (report.deps?.length > 0) {
        out.push('## Dependencies');
        out.push('');
        out.push(
          line([
            `${report.counts.total} total`,
            report.counts.vulnerable > 0 && `**${report.counts.vulnerable} vulnerable**`,
            report.counts.major > 0 && `${report.counts.major} major behind`,
            report.counts.minor > 0 && `${report.counts.minor} minor behind`,
            `checked ${day(report.generatedAt)}`,
          ]),
          '',
        );
        const vulnerable = report.deps.filter(d => d.vulns.length > 0);
        if (vulnerable.length > 0) {
          out.push('Vulnerable packages:');
          for (const d of vulnerable) {
            out.push(`- ${d.name} ${d.specVersion ?? d.raw} (${d.ecosystem})`);
            for (const v of d.vulns) {
              out.push(`  - ${v.id}${v.summary ? `: ${v.summary}` : ''} — ${v.url}`);
            }
          }
          out.push('');
        }
      }
    }
  } catch {
    // Malformed/absent report — skip the section.
  }

  // ── Notes / project memory ──────────────────────────────────────────────
  if (project.notes.trim()) {
    out.push('## Project Notes / Memory');
    out.push('');
    out.push(project.notes.trim());
    out.push('');
  }

  out.push('---');
  out.push(
    '_Operational snapshot only — consult the repository README/docs for architecture and contribution guidelines._',
  );
  out.push('');

  return out.join('\n');
}

/**
 * Standalone dependency report for AI assistants — the "fix my dependencies"
 * prompt. English on purpose, like the main handover doc.
 */
export function buildDepsDoc(projectName: string, report: DepsReport): string {
  const out: string[] = [];
  out.push(`# ${projectName} — Dependency Report`);
  out.push('');
  out.push(
    `> Generated by Nexus from ${report.manifests.join(', ') || 'no manifests'} (checked ${report.generatedAt}). Versions are manifest specs, not lockfile-resolved.`,
  );
  out.push('');

  const vulnerable = report.deps.filter(d => d.vulns.length > 0);
  out.push(
    line([
      `${report.counts.total} dependencies`,
      `${report.counts.vulnerable} vulnerable`,
      `${report.counts.major} major behind`,
      `${report.counts.minor} minor behind`,
      `${report.counts.patch} patch behind`,
    ]),
  );
  out.push('');

  if (vulnerable.length > 0) {
    out.push(`## Vulnerabilities (${vulnerable.length} packages)`);
    out.push('');
    for (const d of vulnerable) {
      out.push(
        `### ${d.name} ${d.specVersion ?? d.raw} (${d.ecosystem}${d.source ? `, ${d.source}` : ''})`,
      );
      for (const v of d.vulns) {
        out.push(`- ${v.id}${v.summary ? `: ${v.summary}` : ''}`);
        out.push(`  ${v.url}`);
      }
      out.push('');
    }
  } else {
    out.push('No known vulnerabilities (per OSV.dev).');
    out.push('');
  }

  const outdated = report.deps
    .filter(d => d.staleness === 'major' || d.staleness === 'minor' || d.staleness === 'patch')
    .sort((a, b) => {
      const rank = { major: 0, minor: 1, patch: 2, current: 3, unknown: 3 } as const;
      return rank[a.staleness] - rank[b.staleness] || a.name.localeCompare(b.name);
    });
  if (outdated.length > 0) {
    out.push(`## Outdated (${outdated.length})`);
    out.push('');
    for (const d of outdated) {
      out.push(
        `- ${d.name}: ${d.specVersion ?? d.raw} → ${d.latest ?? '?'} (${d.staleness}${d.dev ? ', dev' : ''}${d.source ? `, ${d.source}` : ''})`,
      );
    }
    out.push('');
  }

  out.push('---');
  out.push(
    '_Suggested task: address the vulnerable packages first (check each advisory for the patched version), then the major-behind upgrades one at a time, running the test suite between steps._',
  );
  out.push('');
  return out.join('\n');
}

/** Ask for a path and write the document. Returns the path, or null if cancelled. */
export async function saveHandoverDoc(projectName: string, contents: string): Promise<string | null> {
  const safeName = projectName.replace(/[^\p{L}\p{N}_-]+/gu, '-').replace(/^-+|-+$/g, '') || 'project';
  const path = await save({
    defaultPath: `${safeName}-handover.md`,
    filters: [{ name: 'Markdown', extensions: ['md'] }],
  });
  if (path === null) return null;
  await invoke<void>('save_text_file', { path, contents });
  return path;
}
